# Generated by Django 4.2.1 on 2023-05-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dusting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dust', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='L', max_length=1)),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.yarn')),
            ],
        ),
    ]
