# Generated by Django 4.2.1 on 2023-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dusting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dusting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dusting',
            name='date',
            field=models.DateField(verbose_name='Dusting date'),
        ),
    ]
